# Home Assistant Operating System build workflow

name: JH Development build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4.1.1
        id: build_haos_builder
        with:
          context: "{{defaultContext}}:develcontainer"
          file: Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/develcontainer
          cache-from: ghcr.io/${{ github.repository_owner }}/develcontainer:cache
          cache-to: ghcr.io/${{ github.repository_owner }}/develcontainer:cache
          platforms: linux/amd64,linux/arm32v7,linux/arm64v8
          push: true
